### PR TITLE
withDataService: partial entity update

### PR DESCRIPTION
**Pull request by qooco**
This is a changes for DataService methods (create & update & updateAll) to use Partial Entity 

---

Also have question, why update method receives only one argument Entity, 
```
update(entity: Partial<Entity>)
```
is not better?
```
update(id: EntityId, data: Partial<Entity>)
```

### CODE REVIEW

**Comment by qooco** [comment]
A bit busy, no time.

**Comment by rainerhahnekamp** [comment]
Thanks @qooco, the `update` didn't require the id so far, because it wasn't a partial. We'll discuss it internally. I support your changes. The only exception is the create. There, I don't want to have a partial.

**Comment by qooco** [comment]
Ok I Understand about update.

About create, thats too ok, in most cases it is right I think (except such properties as created_at|updated_at). 

So thanks, good luck

**Comment by qooco** [comment]
PR update: only Partial<E> update

**Pull request closed without merging**
